apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawford-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crawford
  template:
    metadata:
      labels:
        app: crawford
    spec:
      containers:
      - name: crawford-container
        image: 300615130618.dkr.ecr.ap-south-1.amazonaws.com/crawford:v8
        ports:
        - containerPort: 8080
